# Surreal Image plus ray for testing distributed setup of our Algos.

# Base on travis minimal container (used for automatic testing).
FROM ducandu/surreal:travis

# Install ray.
RUN pip3 install ray ray[debug] psutil

CMD ["bash"]
